CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "lastname" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "description" varchar(200) NOT NULL,
  "level" varchar(50) NOT NULL,
  "teacher" varchar(100) NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "url" varchar(200) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_roles" (
  "course_id" int NOT NULL,
  "categories_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_roles" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_roles" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

INSERT INTO roles (name) VALUES
('Member'),
('Teacher'),
('Admin');

 INSERT INTO categories (name) VALUES
('Principiantes'),
('Intermedios'),
('Avanzados');


INSERT INTO users (name, lastname, email, password, age, role_id)
VALUES
('Laura', 'Pérez', 'laura@gmail.com', 'Pato8596', 58, 1),
('Alejandra', 'Gomez', 'tere@outlook.com', 'Tere3674', 45, 2),
('Antonia', 'Sánchez', 'antonia@academlo.com', 'Anto8525', 49, 3);


INSERT INTO courses ( title, description, level, teacher)
VALUES
( 'Programación Básica', 'En este curso se enseñarán los conceptos básicos de la programación', 'Principiantes', 'Alejandra'),
( 'Programación Intermedia', 'En este curso se enseñarán los lenguajes como HTML, CSS y JS', 'Intermedios', 'Constanza'),
( 'Programación Avanzada', 'En este curso se enseñarán los lenguajes como NodeJS, SQL, diseñar Bases de Datos y Apis', 'Intermedios', 'Ian');

INSERT INTO courses_video (title, url, course_id)
VALUES
('Programación Básica', 'https:/programacionbasica/academlo.com', 1),
('Programación Intermedia', 'https:/programacionintermedia/academlo.com', 2),
('Programación Avanzada', 'https:/programacionavanzada/academlo.com', 3);

INSERT INTO users_courses (user_id, course_id) VALUES
(1, 2),
(2, 1),
(3, 3);

INSERT INTO courses_roles (course_id, categories_id) VALUES
(1, 1),
(2, 2),
(3, 3);
